export default [
  { 
    "_id": "A101", 
    "title": "Propulsion Assignment", 
    "course": "RS101",
    "description": "Design and analyze a rocket propulsion system including thrust calculations, specific impulse, and fuel efficiency metrics.",
    "points": 100,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  { 
    "_id": "A102", 
    "title": "Combustion Analysis", 
    "course": "RS101",
    "description": "Analyze combustion chamber dynamics, temperature profiles, and pressure distributions in rocket engines.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  { 
    "_id": "A103", 
    "title": "Nozzle Design Project", 
    "course": "RS101",
    "description": "Design an optimal nozzle geometry for a given mission profile. Include CFD analysis and performance predictions.",
    "points": 150,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "May 27 at 11:59pm",
    "dueDateInput": "2024-05-27T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-03",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "fileUpload": true,
    "mediaRecordings": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "123",
    "title": "A1",
    "course": "1234",
    "description": "The assignment is available online\n\nSubmit a link to the landing page of your Web application running on Netlify.\n\nThe landing page should include the following:\n\n- Your full name and section\n- Links to each of the lab assignments\n- Link to the Kanbas application\n- Links to all relevant source code repositories\n\nThe Kanbas application should include a link to navigate back to the landing page.",
    "points": 100,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "234",
    "title": "A2",
    "course": "1234",
    "description": "Create a React application with proper component structure and state management.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "345",
    "title": "A3",
    "course": "1234",
    "description": "Implement Redux state management and integrate with a REST API.",
    "points": 100,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "May 27 at 11:59pm",
    "dueDateInput": "2024-05-27T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-03",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  }
  ,
  
  {
    "_id": "A201",
    "title": "Airfoil Analysis",
    "course": "RS102",
    "description": "Analyze lift and drag characteristics of various airfoil profiles using computational methods and wind tunnel data.",
    "points": 100,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A202",
    "title": "Supersonic Flow Simulation",
    "course": "RS102",
    "description": "Model shock wave formation and analyze supersonic flow patterns around aerospace vehicles.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "fileUpload": true,
    "mediaRecordings": false,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A203",
    "title": "Heat Shield Design",
    "course": "RS102",
    "description": "Design a thermal protection system for atmospheric re-entry considering aerodynamic heating.",
    "points": 150,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "May 27 at 11:59pm",
    "dueDateInput": "2024-05-27T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-03",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": false,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A301",
    "title": "Spacecraft Structure Analysis",
    "course": "RS103",
    "description": "Perform structural analysis of a spacecraft bus including modal analysis and stress calculations.",
    "points": 100,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": false,
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A302",
    "title": "Orbit Transfer Calculation",
    "course": "RS103",
    "description": "Calculate delta-v requirements for various orbital maneuvers including Hohmann transfers.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A303",
    "title": "Mission Design Project",
    "course": "RS103",
    "description": "Design a complete space mission including spacecraft systems, trajectory, and operations plan.",
    "points": 200,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "June 3 at 11:59pm",
    "dueDateInput": "2024-06-03T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-10",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "mediaRecordings": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A401",
    "title": "Organic Synthesis Problem Set",
    "course": "RS104",
    "description": "Complete multi-step synthesis problems and propose mechanisms for organic reactions.",
    "points": 80,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A402",
    "title": "NMR Spectroscopy Lab",
    "course": "RS104",
    "description": "Interpret NMR spectra to determine structures of unknown organic compounds.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A403",
    "title": "Natural Product Synthesis",
    "course": "RS104",
    "description": "Design a synthesis route for a complex natural product molecule.",
    "points": 120,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "May 27 at 11:59pm",
    "dueDateInput": "2024-05-27T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-03",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "fileUpload": true,
    "mediaRecordings": false,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A501",
    "title": "Crystal Field Theory Problems",
    "course": "RS105",
    "description": "Calculate crystal field splitting energies and predict magnetic properties of coordination compounds.",
    "points": 80,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": false,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A502",
    "title": "Synthesis Lab Report",
    "course": "RS105",
    "description": "Synthesize and characterize an inorganic coordination complex.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A503",
    "title": "Catalysis Research Project",
    "course": "RS105",
    "description": "Research and present on a homogeneous catalysis system used in industry.",
    "points": 150,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "June 3 at 11:59pm",
    "dueDateInput": "2024-06-03T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-10",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "mediaRecordings": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A601",
    "title": "Thermodynamics Problem Set",
    "course": "RS106",
    "description": "Solve problems involving entropy, enthalpy, and Gibbs free energy calculations.",
    "points": 80,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A602",
    "title": "Kinetics Experiment",
    "course": "RS106",
    "description": "Determine rate law and activation energy for a chemical reaction.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A603",
    "title": "Computational Chemistry Project",
    "course": "RS106",
    "description": "Use quantum mechanical calculations to predict molecular properties and reaction pathways.",
    "points": 150,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "June 3 at 11:59pm",
    "dueDateInput": "2024-06-03T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-10",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "fileUpload": true,
    "mediaRecordings": false,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A701",
    "title": "Elvish Translation Exercise",
    "course": "RS107",
    "description": "Translate passages between English, Quenya, and Sindarin with grammatical analysis.",
    "points": 100,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": true,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A702",
    "title": "Tengwar Script Practice",
    "course": "RS107",
    "description": "Write original compositions using the Tengwar script system.",
    "points": 80,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A703",
    "title": "Linguistic Analysis Project",
    "course": "RS107",
    "description": "Analyze the linguistic evolution of a Middle-earth language family through the ages.",
    "points": 150,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "June 3 at 11:59pm",
    "dueDateInput": "2024-06-03T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-10",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "mediaRecordings": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A801",
    "title": "Council of Elrond Analysis",
    "course": "RS108",
    "description": "Analyze the diplomatic strategies employed during the Council of Elrond.",
    "points": 100,
    "availableFrom": "May 6 at 12:00am",
    "dueDate": "May 13 at 11:59pm",
    "dueDateInput": "2024-05-13T23:59",
    "availableFromDate": "2024-05-06",
    "availableUntilDate": "2024-05-20",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "textEntry": true,
    "websiteUrl": false,
    "fileUpload": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  },
  {
    "_id": "A802",
    "title": "Alliance Case Study",
    "course": "RS108",
    "description": "Examine a historical alliance in Middle-earth and identify success factors.",
    "points": 100,
    "availableFrom": "May 13 at 12:00am",
    "dueDate": "May 20 at 11:59pm",
    "dueDateInput": "2024-05-20T23:59",
    "availableFromDate": "2024-05-13",
    "availableUntilDate": "2024-05-27",
    "group": "ASSIGNMENTS",
    "displayGradeAs": "Points",
    "submissionType": "Online",
    "fileUpload": true,
    "studentAnnotation": true,
    "assignTo": "Everyone"
  },
  {
    "_id": "A803",
    "title": "Diplomatic Simulation",
    "course": "RS108",
    "description": "Participate in a multi-party diplomatic simulation resolving inter-species conflicts.",
    "points": 200,
    "availableFrom": "May 20 at 12:00am",
    "dueDate": "June 3 at 11:59pm",
    "dueDateInput": "2024-06-03T23:59",
    "availableFromDate": "2024-05-20",
    "availableUntilDate": "2024-06-10",
    "group": "PROJECTS",
    "displayGradeAs": "Percentage",
    "submissionType": "Online",
    "websiteUrl": true,
    "fileUpload": true,
    "mediaRecordings": true,
    "studentAnnotation": false,
    "assignTo": "Everyone"
  }

];